### ISSUE TITLE
Update from dreibein/contao-author-bundle 

### ISSUE THREAD

**Issue by Shoekrates** [sowieso-web/contao-author-bundle#11]
Hi!
In an older installation we used dreibein/contao-author-bundle.
Is there a preferred way to „update“ to your extension to keep the status quo?

My way would be:

- Deinstall package dreibein/contao-author-bundle, leave DB tables as is
- Install package sowieso-web/contao-author-bundle

Any concerns?

**Comment by Xirdion** [comment]
Hi. Yes, this is a good approach. But be careful. Even if the GitHub-Account is called "sowieso-web", for composer you need to use the name **sowieso**.

You could also just update your composer.json file and replace **dreibein** with **sowieso**.

**Comment by Shoekrates** [comment]
Thanks, the second version ran pretty smooth.
