### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by erikherbert** [sowieso-web/contao-author-bundle#9]
Can you Update your Plugin to use in PHP 8.1?

Package dreibein/contao-author-bundle has requirements incompatible with your PHP version, PHP extensions and Composer version:

- dreibein/contao-author-bundle 1.1.0 requires php ^7.4 which does not match your installed version 8.1.3.

**Comment by sowieso-web** [comment]
Hi @erikherbert 
This repository was transferred from dreibein to our account. We will continue the development.
We will try to update the code as soon as possible.

**Comment by Xirdion** [comment]
@erikherbert I have updated the composer.json file so php 8 is now allowed.
